server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: dfklWWHObhUWHEJKHhkjHWKXEHWUIEHXWUIWjhkjHJKWHEJWKeKEhjhKJHEWlhjkjklewkjkljkljewqnnjkbctjkwbtek # 임시 토큰, 나중에 삭제
  expiration_time: 86400000

spring:
  application:
    name: cooper-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:3000'
              - 'http://221.144.190.76:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

      routes:
# USER
        - id: cooper-user
          uri: lb://COOPER-USER
          predicates:
            - Path=/cooper-user/signup, /cooper-user/signin # JwtFilter 제외 목록
          filters:
            - RemoveRequestHeader=Cookie
        - id: cooper-user
          uri: lb://COOPER-USER
          predicates:
            - Path=/cooper-user/**
          filters:
            - JwtFilter
# MEDIA
        - id: cooper-media-websocket
          uri: lb://COOPER-MEDIA
          predicates:
              - Path=/signaling/** # WebSocket 엔드포인트 패턴
        - id: cooper-media-restapi
          uri: lb://COOPER-MEDIA
          predicates:
            - Path=/cooper-media/** # REST API 엔드포인트 패턴
          filters:
            - JwtFilter
# DOCS
        - id: cooper-docs
          uri: lb://COOPER-DOCS
          predicates:
            - Path=/cooper-docs/**ㅋ
          filters:
            - JwtFilter
# CHAT
        - id: cooper-chat
          uri: lb://COOPER-CHAT
          predicates:
            - Path=/cooper-chat/**
          filters:
            - JwtFilter
