server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: cooper-gateway
  cloud:
    gateway:
      routes:
        - id: cooper-user
          uri: lb://COOPER-USER
          predicates:
            - Path=/cooper-user/**
        - id: cooper-media
          uri: lb://COOPER-MEDIA
          predicates:
            - Path=/cooper-media/**
        - id: cooper-docs
          uri: lb://COOPER-DOCS
          predicates:
            - Path=/cooper-docs/**
        - id: cooper-chat
          uri: lb://COOPER-CHAT
          predicates:
            - Path=/cooper-chat/**